[profile.default]
solc = "0.8.30"
ffi = true # Necessary for the HuffNeoDeployer
fs_permissions = [{ access = "read", path = "../tokens/ethereum.json"}]
via-ir = true

[fmt]
sort_imports = true
wrap_comments = true
