[profile.default]
solc = "0.8.33"
evm_version = "osaka"

ffi = true                                                      # Necessary for the HuffNeoDeployer
fs_permissions = [
    { access = "read", path = "../tokens/"},                    # Shared token lists
    { access = "read", path = "test/fixtures/" },               # Local test fixtures
    { access = "write", path = "src/locked/tokens.huff" },      # Processed token list for deployment
    { access = "read", path = "v3-artifacts/" }                 # Deployment artifacts for the Ekubo v3 contracts
]
via_ir = true

[fmt]
sort_imports = true
wrap_comments = true

[lint]
exclude_lints = ["unsafe-cheatcode"]
