name: Test
on: [push, pull_request]
jobs:
  test-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - run: npm test
  test-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - uses: cakevm/huff-neo-toolchain@v1
        with:
          version: 1.3.6
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
        working-directory: ./sdk
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.3
      - run: forge test --gas-snapshot-check=true
        env:
          MAINNET_RPC_URL_OR_ALIAS: ${{ secrets.MAINNET_RPC_URL }}
