name: Test
on: [push, pull_request]
jobs:
  test-sdk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: sdk/package-lock.json
      - run: npm ci
      - run: npm test
